version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - DATABASE_URL=sqlite:///./data/feedback.db
      - SECRET_KEY=your-secret-key-change-in-production
    restart: unless-stopped